// ------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by PersistorCodeGenerator.
    //     DO NOT EDIT. Any changes will be lost when the file is regenerated.
    // </auto-generated>
    // ------------------------------------------------------------------------------
    using UnityEngine;
    [DataFor(typeof(Enemy))]
    [System.Serializable]
    public partial class Enemy__data
    {
        public string gameUnitId;
    public string unitName;
    public int health;
    public float speed;
    public Vector3 myVectorThree;
    public EnemyPersistor enemyPersistor;

        public void CopyToData(Enemy unit)
        {
            PersistorIdAssigner.AssignIdIfNeeded(unit);
            this.gameUnitId = unit.gameUnitId;
        this.unitName = unit.unitName;
        this.health = unit.health;
        this.speed = unit.speed;
        this.myVectorThree = unit.myVectorThree;
            if (enemyPersistor != null) enemyPersistor.CopyToData(unit);
            
        }

        public void CopyFromData(Enemy unit)
        {
            unit.gameUnitId = this.gameUnitId;
        unit.unitName = this.unitName;
        unit.health = this.health;
        unit.speed = this.speed;
        unit.myVectorThree = this.myVectorThree;
            if (enemyPersistor != null) enemyPersistor.CopyFromData(unit);
            
        }
    }