// ------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by PersistorCodeGenerator.
    //     DO NOT EDIT. Any changes will be lost when the file is regenerated.
    // </auto-generated>
    // ------------------------------------------------------------------------------
    using UnityEngine;
    [CreateAssetMenu(menuName = "Persistor Presets/EnemyPreset")]
    public partial class Enemy_Preset : ScriptableObject
    {
        public string unitName;
    public int health;
    public float speed;
    public Vector3 myVectorThree;

        public void CopyFromPreset(Enemy unit)
        {
            unit.unitName = this.unitName;
        unit.health = this.health;
        unit.speed = this.speed;
        unit.myVectorThree = this.myVectorThree;
        }
    }
    