// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AdaptorCodeGenerator.
//     DO NOT EDIT. Any changes will be lost when the file is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System.Collections.Generic;
using UnityEngine;
using PersistorEngine;
[CreateAssetMenu(menuName = "Adaptor Presets/CollectionHolderPreset")]
public partial class CollectionHolder_Preset : ScriptableObject
{
    public List<string> ABunchOfStrings;

    public void CopyFromPreset(CollectionHolder unit)
    {
        unit.ABunchOfStrings = this.ABunchOfStrings;
    }
}