// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AdaptorCodeGenerator.
//     DO NOT EDIT. Any changes will be lost when the file is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using UnityEngine;
using PersistorEngine;
[CreateAssetMenu(menuName = "Adaptor Presets/EnemyPreset")]
public partial class Enemy_Preset : ScriptableObject
{
    public string unitName;
    public int health;
    public float speed;
    public Vector3 myVectorThree;
    public MyType myType;
    public MySharedData mySharedData;

    public void CopyFromPreset(Enemy unit)
    {
        unit.unitName = this.unitName;
        unit.health = this.health;
        unit.speed = this.speed;
        unit.myVectorThree = this.myVectorThree;
        unit.myType = this.myType;
        unit.mySharedData = this.mySharedData;
    }
}