// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by PersistorCodeGenerator.
//     DO NOT EDIT. Any changes will be lost when the file is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using UnityEngine;
using PersistorEngine;
using PersistorEngine.Internal;
[DataFor(typeof(Enemy))]
[System.Serializable]
public partial class Enemy__Data
{
    public string persistorId;
    public string unitName;
    public int health;
    public float speed;
    public Vector3Persistor myVectorThreePersistor = new();
    public MyTypeAdaptor myTypePersistor = new();
    public string mySharedDataId;
    public EnemyAdaptor enemyPersistor = new();

    public void CopyToData(Enemy unit)
    {
        this.persistorId = unit.persistorId;
        this.unitName = unit.unitName;
        this.health = unit.health;
        this.speed = unit.speed;
        myVectorThreePersistor.CopyToData(unit.myVectorThree);
        if (unit.myType != null) myTypePersistor.CopyToData(unit.myType);
        this.mySharedDataId = unit.mySharedData != null ? unit.mySharedData.persistorId : null;
        enemyPersistor.CopyToData(unit);
    }

    public void CopyFromData(Enemy unit)
    {
        unit.persistorId = this.persistorId;
        unit.unitName = this.unitName;
        unit.health = this.health;
        unit.speed = this.speed;
        myVectorThreePersistor.CopyFromData(ref unit.myVectorThree);
        if (unit.myType != null) myTypePersistor.CopyFromData(unit.myType);
        unit.mySharedData = PersistorRegistry.Resolve<MySharedData>(this.mySharedDataId);
        enemyPersistor.CopyFromData(unit);
    }
}