// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AdaptorCodeGenerator.
//     DO NOT EDIT. Any changes will be lost when the file is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using UnityEngine;
using PersistorEngine;
[CreateAssetMenu(menuName = "Adaptor Presets/GirlPreset")]
public partial class Girl_Preset : ScriptableObject
{
    public string GirlName;
    public string Mood;

    public void CopyFromPreset(Girl unit)
    {
        unit.GirlName = this.GirlName;
        unit.Mood = this.Mood;
    }
}