// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by PersistorCodeGenerator.
//     DO NOT EDIT. Any changes will be lost when the file is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using PersistorEngine;
using PersistorEngine.Internal;
[DataFor(typeof(MySharedData))]
[System.Serializable]
public partial class MySharedData__Data
{
    public string persistorId;
    public string myEmbeddedDataString;

    public void CopyToData(MySharedData unit)
    {
        this.persistorId = unit.persistorId;
        this.myEmbeddedDataString = unit.myEmbeddedDataString;
        
    }

    public void CopyFromData(MySharedData unit)
    {
        unit.persistorId = this.persistorId;
        unit.myEmbeddedDataString = this.myEmbeddedDataString;
        
    }
}