// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AdaptorCodeGenerator.
//     DO NOT EDIT. Any changes will be lost when the file is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using UnityEngine;
using PersistorEngine;
[CreateAssetMenu(menuName = "Adaptor Presets/MySharedDataPreset")]
public partial class MySharedData_Preset : ScriptableObject
{
    public string myEmbeddedDataString;

    public void CopyFromPreset(MySharedData unit)
    {
        unit.myEmbeddedDataString = this.myEmbeddedDataString;
    }
}
