// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AdaptorCodeGenerator.
//     DO NOT EDIT. Any changes will be lost when the file is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using PersistorEngine;
using PersistorEngine.Internal;
[DataFor(typeof(MyType))]
[System.Serializable]
public partial class MyType__Data
{
    public string persistorId;
    public int someValue;
    public MyTypeAdaptor myTypeAdaptor = new();

    public void CopyToData(MyType unit)
    {
        this.persistorId = unit.persistorId;
        this.someValue = unit.someValue;
        myTypeAdaptor.CopyToData(unit);
    }

    public void CopyFromData(MyType unit)
    {
        unit.persistorId = this.persistorId;
        unit.someValue = this.someValue;
        myTypeAdaptor.CopyFromData(unit);
    }
}