// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AdaptorCodeGenerator.
//     DO NOT EDIT. Any changes will be lost when the file is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using UnityEngine;
using PersistorEngine;
[CreateAssetMenu(menuName = "Adaptor Presets/MyTypePreset")]
public partial class MyType_Preset : ScriptableObject
{
    public int someValue;

    public void CopyFromPreset(MyType unit)
    {
        unit.someValue = this.someValue;
    }
}