// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AdaptorCodeGenerator.
//     DO NOT EDIT. Any changes will be lost when the file is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System.Collections.Generic;
using UnityEngine;
using PersistorEngine;
[CreateAssetMenu(menuName = "Adaptor Presets/PersistorListTestPreset")]
public partial class PersistorListTest_Preset : ScriptableObject
{
    public List<int> Values;

    public void CopyFromPreset(PersistorListTest unit)
    {
        unit.Values = this.Values;
    }
}