// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AdaptorCodeGenerator.
//     DO NOT EDIT. Any changes will be lost when the file is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System.Collections.Generic;
using UnityEngine;
using PersistorEngine;
[CreateAssetMenu(menuName = "Adaptor Presets/PersistorGrowingSpherePreset")]
public partial class PersistorGrowingSphere_Preset : ScriptableObject
{
    public List<PersistorGrowingSphere> Children;

    public void CopyFromPreset(PersistorGrowingSphere unit)
    {
        unit.Children = this.Children;
    }
}