// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AdaptorCodeGenerator.
//     DO NOT EDIT. Any changes will be lost when the file is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System.Collections.Generic;
using UnityEngine;
using PersistorEngine;
[CreateAssetMenu(menuName = "Adaptor Presets/PursePreset")]
public partial class Purse_Preset : ScriptableObject
{
    public List<string> items;

    public void CopyFromPreset(Purse unit)
    {
        unit.items = this.items;
    }
}